config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/about' => 'home#about'
  post '/' => 'home#get_summoner'

  get '/champions' => 'champions#index' # for seeding Champion db
  get '/:summoner_id/summary' => 'home#summary', as: 'summary'

end

app/models/champion.rb
class Champion < ActiveRecord::Base
  def self.find_or_create_by(champions)
    champions = champions['data']

    champions.each do |champion|
      name = champion[0]
      champ = self.find_or_initialize_by(lol_id: champion[1]['id'])
      champ.name = name
      champ.image = champion[1]['image']['full']
      champ.lol_id = champion[1]['id']
      champ.title = champion[1]['title']
      champ.tags = champion[1]['tags']
      champ.save ? champ : false
    end

  end
end

#
# def self.find_or_create_by(followee_hash)
#   followee = self.find_or_initialize_by(native_id: followee_hash[:id])
#   followee.source = followee_hash[:source]
#   followee.handle = followee_hash[:username]
#   followee.avatar_url = followee_hash[:picture] || followee_hash[:avatar_url]
#
#   followee.save ? followee : false
# end

app/controllers/application_controller.rb
require 'api_helper'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/champions_controller.rb
require 'api_helper'

class ChampionsController < ApplicationController

  def index
    @champions = ApiHelper.new.get_champions
    Champion.find_or_create_by(@champions)

    redirect_to root_path, notice: "Sucessfully checked for new champions."
  end
end

app/controllers/home_controller.rb
require 'api_helper'

class HomeController < ApplicationController
  PROFILE_ICON = 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/profileicon/'

  def index
  end

  def get_summoner
    if params[:summoner_name] == ""
      flash[:error] = "We need your summoner name to find your stats.
      We're not mind readers!"
      render 'index'
    else
      response = ApiHelper.new.get_summoner_id(params[:summoner_name])
      if response.parsed_response.include?("400") || response.parsed_response.include?("401") || response.parsed_response.include?("429") || response.parsed_response.include?("500") || response.parsed_response.include?("503")
        flash[:error] = "Something went wrong and Riot Games is not responding.
        Please try again later."
        render 'index'
      elsif response.parsed_response.include?("404")
        flash[:error] = "Summoner information not found. Please try again."
        render 'index'
      else
         @summoner = parse_response(response)
         render 'summoner'
      end
    end
  end

  def summary
    @summary = ApiHelper.new.summoner_summary(params[:summoner_id])
    @recent = ApiHelper.new.recent(params[:summoner_id])
    @recent_summary = ApiHelper.new.average_stats(@recent)
  end

  def parse_response(response)
    screen_name = response.first[1]['name']
    id = response.first[1]['id']
    level = response.first[1]['summonerLevel']
    icon = PROFILE_ICON + response.first[1]["profileIconId"].to_s + '.png'

    return {screen_name: screen_name, id: id, level: level, icon: icon}
  end

  def about
    # legal statement
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def winning_image(wins)
    if wins >= 50
      image_tag('happy.png', size: '64x46')
    else
      image_tag('sad.png', size: '64x64')
    end
  end

  def did_you_win(win_field)
    if win_field == true
      image_tag('thumbup.jpg', height: '80', width: '100')
    else
      image_tag('thumbdown.jpg', height: '90', width: '100')
    end
  end

  def gold_display(amount)
    gold_rows = ''
    scaled_down = (amount/1000)
    scaled_down = scaled_down.round

    scaled_down.times { gold_rows += image_tag('coin.jpg', size: '42x64') }

    return gold_rows.html_safe
  end

  def convert_playtime(time_in_sec)
    min = (time_in_sec/60)
    sec = time_in_sec.modulo(60)

    return "#{min}:#{sec}"
  end
end

app/views/champions/index.html.erb
<h1> HERE ARE YOUR CHAMPIONS, MY FRIEND!!</h1>
<%= @champions %>

app/views/home/about.html.erb
<div class='about'>
  <div class='col-md-5'>
    <section>
      <h2>About LOL Killuns</h2>
      <p>
        This started as a project during a break from attending
        <%= link_to 'Ada Developers Academy', 'http://adadevelopersacademy.org/' %>.
        I couldn't put it down until I had a version that was live and I was happy with.
      </p>
      <p>
        I had a lot of fun with LOL Killuns and working with the League of Legend API.
        I hope you will enjoy it too.
      </p>
    </section>
    <section>
      <h3>Legal Statement </h3>
      <p>
        LOL Killuns isn't endorsed by Riot Games and
        doesn't reflect the views or opinions of Riot Games
        or anyone officially involved in producing or managing
        League of Legends. League of Legends and Riot Games are
        trademarks or registered trademarks of Riot Games, Inc.
        League of Legends © Riot Games, Inc.
      </p>
    </section>
  </div>
</div>

app/views/home/index.html.erb
<div class='index'>
  <div class='input-section'>
    <h1>League of Legends Killuns</h1>

    <h3> Please enter summoner name below. </h3>
    <%= flash[:error]%>

    <%= form_tag  %>
    <%= text_field_tag :summoner_name %>

    <%= submit_tag 'Submit', class: 'btn btn-default' %>
  </div>
</div>

app/views/home/summary.html.erb
<h1>Your Summary</h1>
<div class='row'>
  <div class="col-md-6">
    <h2>Average Over <%= @recent.count %> Games</h2>
    <p> <%= winning_image(@recent_summary[:win]) %> Winning <%= @recent_summary[:win] %>% of the Time </p>
    <p> <%= image_tag('skull.jpg', size: '63x64')%> <%= @recent_summary[:championskilled] %> Kills </p>
    <p> <%= image_tag('coin.jpg', size: '42x64') %> Gold <%= @recent_summary[:gold] %> </p>
    <p> <%= image_tag('x.png', size: '64x63')%>  <%= @recent_summary[:deaths] %> Deaths </p>
    <p> <%= image_tag('handshake.png', size: '64x32') %> <%= @recent_summary[:assists] %> Assists </p>
    <p> <%= image_tag('explosion.png', size: '64x58') %> <%= @recent_summary[:totalDamageDealtToChampions] %> Damage Dealt </p>
  </div>
  <div class="col-md-6">
    <h2>All Time Summary</h2>
    <table class='table'>
      <th>Mode </th>
      <th>Wins/Kills/Assists </th>
      <tr>
      <% @summary.each do |set| %>
        <td><%= set["playerStatSummaryType"] %> </td>
        <td><%= set["wins"] %> / <%= set["aggregatedStats"]["totalChampionKills"] %> / <%= set["aggregatedStats"] ["totalAssists"]%> </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

<%= render partial: 'shared/game', locals: {recent: @recent} %>

app/views/home/summoner.html.erb
<h1>Summoner Profile </h1>
<h2>
  <%= image_tag(@summoner[:icon]) %>
  <%= @summoner[:screen_name] %>
  Level <%= @summoner[:level] %>
</h2>

<%= link_to "Summary", summary_path(@summoner[:id]) %>

<p>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LOL Killuns</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- google font -->
  <link href='https://fonts.googleapis.com/css?family=Arbutus+Slab' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <%= yield %>


    <footer>
      Brittany Walentin © <%= Time.now.year %> |
      <%= link_to 'Find Another Summoner', root_path %> | 
      <%= link_to "About", about_path %>
    </footer>
  </div>
</body>
</html>

app/views/shared/_game.html.erb
<h2>Most Recent Games Played </h2>
<table class='table table-striped'>

<% recent.each do |game| %>
  <tr rowspan='3'>
    <td>
      <p><%= (game[:date]).strftime('%m/%d/%Y %l:%M %p') %></p>
      <p>Game Length: <%= convert_playtime(game[:timePlayed]) %></p>
    </td>
    <td><%= game[:gameMode] %> </td>
    <td>
      <p><%= image_tag(game[:champion_image]) %> </p>
      <p><%= game[:champion] %> </p>
    </td>
    <td>
      <p><%= game[:championskilled] %>/<%= game[:deaths] %>/<%= game[:assists] %> </p>
      <p>K/D/A</p>
    </td>
    <td>
      <p><%= game[:totalDamageDealtToChampions] %> Damage Dealt </p>
      <p><%= game[:killingsprees] %> Killing Spree(s) </p>
      <p>Largest Multikill: <%= game[:largestMultiKill] %> </p>
      <p><%= game[:crowdControl] %> Crowd Control </p>
      <p><%= game[:totalHeal] %> Total Healed </p>
    </td>
    <td>
      <%= image_tag(game[:item0]) %>
      <%= image_tag(game[:item1]) %>
      <%= image_tag(game[:item2]) %>
      <%= image_tag(game[:item3]) %>
      <%= image_tag(game[:item4]) %>
      <%= image_tag(game[:item5]) %>
    </td>

    <td>
      <%= gold_display(game[:gold]) %>
      <%= game[:gold] %> Gold
    </td>
    <td><%= game[:turretsKilled] %> Turret(s) Takedown </td>
    <td> <%= did_you_win(game[:win]) %> </td>
  </tr>
<% end  %>
</table>